#pragma once
#include "meta/serializer/serializer.h"
#include "_generated\serializer\vector3.serializer.gen.h"
#include "_generated\serializer\Light_component.serializer.gen.h"
#include "_generated\serializer\Transform_component.serializer.gen.h"
#include "_generated\serializer\object_asset.serializer.gen.h"
#include "_generated\serializer\scene_asset.serializer.gen.h"
#include "_generated\serializer\mesh_asset.serializer.gen.h"
#include "_generated\serializer\component.serializer.gen.h"
#include "_generated\serializer\world_asset.serializer.gen.h"
#include "_generated\serializer\quaternion.serializer.gen.h"
#include "_generated\serializer\vector2.serializer.gen.h"
#include "_generated\serializer\Mesh_component.serializer.gen.h"
#include "_generated\serializer\Camera_component.serializer.gen.h"

